language: node_js

node_js:
  - 10
  
os:
  - windows
  
before_install:
  - npm install
  
cache:
  npm: false

script:
  - ./deploy.bat
  
after_success:
  - git config user.email "azeezadewale98@gmail.com"
  - git config user.name "Travis CI"
  - git add .
  - git commit -m "Travis build=${TRAVIS_BUILD_NUMBER}. Auto update from Travis CI"
  - >
    if ($(git log -1 --pretty=format:'%an') -ne "Travis CI")
    {
      git push https://Thecarisma:${GITHUB_TOKEN}@github.com/quickutils/language-colors.git HEAD:master
    }