language: node_js

node_js:
  - 10
  
os:
  - windows
  
before_install:
  - npm install
  
cache:
  npm: false

script:
  - ./deploy.bat
  - npm install -g json
  - json -I -f package.json -e 'this.version="1."+process.env.TRAVIS_BUILD_NUMBER+".0"'
  - cat package.json
  - npm pack
  
after_success:
  - git config --local user.email "azeezadewale98@gmail.com"
  - git config --local user.name "Travis CI"
  - export NAME=$(git log -1 --pretty=format:'%an')
  - git add .
  - git commit -m "Travis build=${TRAVIS_BUILD_NUMBER}. Auto update from Travis CI"
  # - if [ "$NAME" != "Travis CI" ]; then git push https://Thecarisma:${GITHUB_TOKEN}@github.com/quickutils/language-colors.git HEAD:master; fi
  
before_deploy:
  - git config --local user.email "azeezadewale98@gmail.com"
  - git config --local user.name "Travis CI"
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - echo $TRAVIS_TAG
  - git tag $TRAVIS_TAG
  
deploy:
  - provider: releases
    skip_cleanup: true
    api_key: $GITHUB_TOKEN
    file_glob: true
    body: |
     The colors are updated monthly. All the colors can be viewed [here](https://quickutils.github.io/language-colors/language-colors.html).
     
     [CSS List of Programming Languages colors values. Foreground and Background](https://github.com/quickutils/language-colors/wiki/CSS-List-of-Programming-Languages-colors-values.-Foreground-and-Background)
         
     [NodeJS List of Programming Languages colors values](https://github.com/quickutils/language-colors/wiki/NodeJS-List-of-Programming-Languages-colors-values)
         
     [Browser JavaScript List of Programming Languages colors values](https://github.com/quickutils/language-colors/wiki/Browser-JavaScript-List-of-Programming-Languages-colors-values)
        
    file:
    - "language-colors.css"
    - "language-colors.js"
    - "language-colors-1.${TRAVIS_BUILD_NUMBER}.0.tgz"
    - "language-colors.ps1"
  # - provider: npm
    # email: "azeezadewale98@gmail.com"
    # api_key: "${NPM_TOKEN}"
    # allow_failure: true
    # skip_cleanup: true
    # on:
      # branch: master