language: node_js

node_js:
  - 10
  
os:
  - windows
  
before_install:
  - npm install
  
cache:
  npm: false

script:
  - ./deploy.bat
  
after_success:
  - git config --global user.email "travis@travis-ci.org"
  - git config --global user.name "Travis CI"
  - git add .
  - git commit -m "Travis build: ${TRAVIS_BUILD_NUMBER}, Auto update from Travis CI."
  - git remote add origin-pages https://${GITHUB_TOKEN}@github.com/quickutils/language-colors.git
  - git push --set-upstream origin-pages master