language: node_js

node_js:
  - 10
  
os:
  - windows
  
before_install:
  - npm install
  
cache:
  npm: false

script:
  - ./deploy.bat
  - npm install -g json
  - json -I -f package.json -e 'this.version="1."+process.env.TRAVIS_BUILD_NUMBER+".0"'
  - cat package.json
  
after_success:
  - git config user.email "azeezadewale98@gmail.com"
  - git config user.name "Travis CI"
  - NAME=$(git log -1 --pretty=format:'%an')
  - git add .
  - git commit -m "Travis build=${TRAVIS_BUILD_NUMBER}. Auto update from Travis CI"
  - if [ "$NAME" != "Travis CI" ]; then git push https://Thecarisma:${GITHUB_TOKEN}@github.com/quickutils/language-colors.git HEAD:master; fi
  
deploy:
  - provider: npm
    email: "azeezadewale98@gmail.com"
    api_key: "${NPM_TOKEN}"
    on:
      branch: master
      condition: "$(git log -1 --pretty=format:%an) = 'Travis CI'"