language: node_js

node_js:
  - 10
  
os:
  - windows
  
branches:
  only:
    - master
  
before_install:
  - npm install
  
cache:
  npm: false

script:
  - export NAME=$(git log -1 --pretty=format:'%an')
  - ./exec.bat
  - npm install -g json
  #- if [ "$NAME" != "Travis CI" ]; then json -I -f package.json -e 'this.version="1."+process.env.TRAVIS_BUILD_NUMBER+".0"'; fi
  - json -I -f package.json -e 'this.version="1."+process.env.TRAVIS_BUILD_NUMBER+".0"';
  - cat package.json
  - npm pack
  
after_success:
  - export NAME=$(git log -1 --pretty=format:'%an')
  - git config --local user.email "iamthecarisma@gmail.com"
  - git config --local user.name "Travis CI"
  - git add .
  - git commit -m "Travis build=${TRAVIS_BUILD_NUMBER}. Auto update from Travis CI"
  #- if [ "$NAME" != "Travis CI" ]; then git push https://Thecarisma:${GITHUB_TOKEN}@github.com/kujitegemea/language-colors.git HEAD:master; fi
  - git push https://Thecarisma:${GITHUB_TOKEN}@github.com/kujitegemea/language-colors.git HEAD:master;
  
before_deploy:
  if ! [[ $TRAVIS_TAG ]]; then
    export TRAVIS_TAG="v1.$TRAVIS_BUILD_NUMBER.0" &&
    git config --local user.email "iamthecarisma@gmail.com" &&
    git config --local user.name "Travis CI" &&
    git tag $TRAVIS_TAG;
  fi
  
deploy:
  - provider: releases
    skip_cleanup: true
    api_key: $GITHUB_TOKEN
    file_glob: true
    allow_failure: true
    body: The colors are updated monthly. All the colors can be viewed [here](https://kujitegemea.github.io/language-colors/language-colors.html).
    file:
    - "language-colors.css"
    - "language-colors.js"
    - "language-colors-1.${TRAVIS_BUILD_NUMBER}.0.tgz"
    - "language-colors.ps1"
  - provider: npm
    email: "iamthecarisma@gmail.com"
    api_key: "${NPM_TOKEN}"
    edge:
      source: 'native-api/dpl'
      branch: 'fix_eaccess'
    skip_cleanup: true
    on:
      branch: master