name: Breath

on:
  push:
  schedule:
    # Runs "at every 2nd minute" (see https://crontab.guru)
    - cron: "*/10 * * * *"
jobs:
  build:
    name: Breath
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate Source Codes
        run: |
          sudo apt-get update
          sudo apt-get install -y wget apt-transport-https software-properties-common
          wget -q "https://packages.microsoft.com/config/ubuntu/$(lsb_release -rs)/packages-microsoft-prod.deb"
          sudo dpkg -i packages-microsoft-prod.deb
          sudo apt-get update
          sudo apt-get install -y powershell
          pwsh -noprofile -executionpolicy bypass -file language-colors.ps1
          cp ./language-colors.css ./docs/
          cp ./language-colors.js ./docs/
          ls -l ./docs/

      # should push to main branch
      - name: Changelog
        uses: scottbrenner/generate-changelog-action@master
        id: Changelog
        env:
          REPO: ${{ github.repository }}

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "v2.${{ github.run_attempt }}.${{ github.run_number }}"
          prerelease: false
          title: "v2.${{ github.run_attempt }}.${{ github.run_number }}"
          files: |
            language-colors.css
            language-colors.js
            language-colors.ps1
